version: '3'

services:
  neo4j:
    container_name: neo4j
    image: neo4j:community
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
    environment:
      NEO4J_AUTH: none

    networks:
      extnetwork:
        ipv4_address: 172.16.0.201

include:
  - ../network.yml 
