version: '3'

services:
  minio:
    restart: always
    container_name: imgproxy
    image: darthsim/imgproxy:v3
    ports:
      - 9999:8080
    volumes:
      - ./data:/app/images
    environment:
      - IMGPROXY_LOCAL_FILESYSTEM_ROOT=/app/images
    env_file:
      - ./env/s3.env
    networks:
      extnetwork:
        ipv4_address: 172.16.0.250

include:
  - ../network.yml 
