version: "3"
services:
  redis:
    image: rabbitmq:3-management # 基础镜像
    container_name: rabbitmq # 容器名称
    restart: always
    ports: # 映射端口，对外提供服务
      - 5672:5672 # tcp 端口
      - 15672:15672 # 管理端端口
    stdin_open: true # 标准输入打开
    tty: true # 后台运行不退出
    privileged: true # 拥有容器内命令执行的权限
    # 映射数据卷，配置目录
    volumes: [
        "./data:/var/lib/rabbitmq",
    ]
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    networks:
      extnetwork:
        ipv4_address: 172.16.0.238

include:
  - ../network.yml 
