version: '3'
services:
  es01:
    image: elasticsearch:7.10.1
    container_name: es01
    restart: always
    environment:
      - node.name=es01
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es/config:/usr/share/elasticsearch/config
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
  kibana01:
    image: kibana:7.10.1
    container_name: kibana01
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./kibana/config:/usr/share/kibana/config
    ports:
      - 5601:5601
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
