version: "3"
services:
  nacos:
    hostname: nacos
    container_name: nacos
    image: nacos/nacos-server:v2.2.3
    volumes:
      - ./logs:/home/nacos/logs
      - ./conf:/home/nacos/conf
    ports:
      - "8848:8848"
      - "9848:9848"
    env_file:
      - ./env/nacos-embedded.env
    restart: always
