version: "3"
services:
  splash:
    image: scrapinghub/splash:3.5
    container_name: splash
    restart: always
    ports: 
      - 8050:8050
    logging:
      options:
        max-size: '100m'
        max-file: '10'
    networks:
      extnetwork:
        ipv4_address: 172.16.0.238

include:
  - ../network.yml 
