version: "3"
services:
  mysql-master:
    restart: always
    privileged: true
    image: mysql:5.7
    container_name: spider-mysql
    volumes:
     - ./mysql/var/lib/mysql:/var/lib/mysql
    environment:
     - "MYSQL_ROOT_PASSWORD=123456"
     - "TZ=Asia/Shanghai"
    ports:
     - 3306:3306
  
  redis:
    image: redis:7.2 # 基础镜像
    container_name: spider-redis # 容器名称
    restart: always
    environment: # 环境变量
      - TZ=Asia/Chongqing
      #- LANG=en_US.UTF-8
    ports: # 映射端口，对外提供服务
      - 6379:6379 # redis的服务端口
    stdin_open: true # 标准输入打开
    tty: true # 后台运行不退出
    privileged: true # 拥有容器内命令执行的权限
    # 映射数据卷，配置目录
    volumes: [
        "./redis/data:/data",
        "./redis/conf/redis.conf:/etc/redis/redis.conf",
    ]
    command: [
        "redis-server",
        "/etc/redis/redis.conf"
    ]
    logging:
      options:
        max-size: '100m'
        max-file: '10'

  splash:
    image: scrapinghub/splash:3.5
    container_name: splash
    restart: always
    ports: 
      - 8050:8050
    logging:
      options:
        max-size: '100m'
        max-file: '10'
