version: '3'

services:
  portainer:
    restart: always
    container_name: portainer
    image: portainer/portainer-ce:2.21.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    networks:
      extnetwork:
        ipv4_address: 172.16.0.246

include:
  - ../network.yml 
