version: '3'
services: 
  mysql-master: 
    restart: always
    privileged: true
    image: postgres:13.16
    container_name: postgresql 
    volumes: 
      - ./data:/var/lib/postgresql/data/pgdata 
    environment: 
      - "POSTGRES_PASSWORD=123456"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    ports: 
      - 5432:5432 
    networks:
      extnetwork:
        ipv4_address: 172.16.0.240

include:
  - ../network.yml 
