version: '3'

services:
  minio:
    restart: always
    container_name: minio
    image: bitnami/minio:2023
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=asdfghjkl
    networks:
      extnetwork:
        ipv4_address: 172.16.0.249

include:
  - ../network.yml 

volumes:
  minio_data:
    driver: local
